version: '1.0'
services:
  paypal-back:
    container_name: paypal-back
    image: node:16.14
    restart: always
    user: node
    ports:
      - 3001:3001
    environment:
      - CLIENT_ID=AUboM47lH3jM7MFwBR5v_5mQ7PmInBC2qQGi2ZnIp5PvCyP3kZADBh1TFpOTjWy3iuB25gM-OZrZ5mZZ
      - APP_SECRET=ENjmTpsYZQQcBOHtISV0wko08a8RnusRtkEMElwH16KQuZ9SG7fKUJZv9oJGcbXjzemWbuQCSCe1GM5S
      - URL_BASE=https://api-m.sandbox.paypal.com
      - NODE_ENV=developing
      - PORT=3001
      - HOST=""
    volumes:
      - ./:/app
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true
